alias em='emacs -nw'
alias cdco='cd ~/Documents/code'
alias cdke='cd ~/Documents/kevalin/code/'
alias sem='sudo emacs -nw'
alias ga='git add'
alias co='git checkout'
alias gsw='git switch'
alias gp='git push'
alias gb='git branch'
alias gl='git log'
alias glp='git log --pretty=format:"%Cred%h%Creset - %Cgreen%an%Creset, %ar : %s"'
alias gs='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gpu='git pull'
alias memuse='ps -o rss,command | grep -v peruser | awk "{sum+=\$1} END {print sum/1024}"'

alias vpn='protonvpn-cli c -f'
alias vpnt='protonvpn-cli c --tor'
alias vpns='protonvpn-cli s'
alias vpnx='protonvpn-cli disconnect'
alias vpnes='protonvpn-cli connect --cc ES'
alias vpnuk='protonvpn-cli connect --cc UK'
alias vpnus='protonvpn-cli connect --cc US'


alias pipe='pipenv shell'
alias cdkey='cd /keybase/'
alias sco='~/./startcoding.sh'
alias backit='~/Documents/code/bash_scripts/back/backups.sh -all'
alias backits='/media/dersu/ExtraDrive1/code/bash_scripts/backups/secure_backup.sh'
alias python='python3'
alias updates='sudo apt update && printf "\n\n" && sudo apt upgrade && printf "\n\n" && sudo apt autoremove'
alias dud='_betterdu(){ du -h -d 1 "$1" | sort -h;}; _betterdu'
alias antivirus='cd ~ && clamscan --infected --recursive .'
alias lastfiles='find . -type f -print0 | xargs -0 stat --format "%Y :%y %n" | sort -nr | cut -d: -f2- | head -n 20'
alias drop='cd && ~/.dropbox-dist/dropboxd &'